#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --mem-per-cpu=3500MB
#SBATCH --time=120:00:00
#SBATCH --partition=sla-prio
#SBATCH --account=sbs5563_bc
#SBATCH --output=slurm.out
#SBATCH --error=slurm.err
#SBATCH --job-name=pytheos-MgCoNiCuZnO-example

export UCX_TLS=all

cd $SLURM_SUBMIT_DIR
module purge
module use /storage/icds/RISE/sw8/modules/
module load vasp/vasp-6.4.1v

eval "$(conda shell.bash hook)"
conda activate pytheos

python cstdn.py