#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --mem-per-cpu=5000MB
#SBATCH --time=72:00:00
#SBATCH --partition=sla-prio
#SBATCH --account=ixd4_s_sc
#SBATCH --output=slurm.out
#SBATCH --error=slurm.err
#SBATCH --job-name=vasp-calc

export UCX_TLS=all

cd $SLURM_SUBMIT_DIR
module purge
module use /storage/icds/RISE/sw8/modules/
module load vasp/vasp-6.4.1v

eval "$(conda shell.bash hook)"
conda activate pytheos

python cstdn.py